[package]
name = "sim-runtime"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tracing = { workspace = true }
bevy_ecs = { workspace = true }
sim-core = { path = "../sim-core" }
sim-econ = { path = "../sim-econ" }
sim-ai = { path = "../sim-ai" }

[dev-dependencies]
criterion = { workspace = true }
