[package]
name = "sim-ai"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
sim-core = { path = "../sim-core" }
sim-econ = { path = "../sim-econ" }

[dev-dependencies]
proptest = { workspace = true }
