name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint
        run: just lint
      - name: Test
        run: just test
      - name: Build
        run: just build
      - name: Commit message guard
        run: |
          MSG=$(git log -1 --pretty=%s)
          echo "Last commit: $MSG"
          if ! echo "$MSG" | grep -Eq '^(feat|fix|chore|docs|test|refactor|perf|ci)(\([\w\-]+\))?: .+'; then
            echo "Commit message does not follow conventional format" >&2
            exit 1
          fi
