name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint
        run: just lint
      - name: Test
        run: just test
      - name: Frontend deps (pnpm)
        run: pnpm install --frozen-lockfile=false
        working-directory: apps/mgmt-ui/web
      - name: Frontend tests (vitest jsdom)
        run: pnpm vitest run --environment jsdom
        working-directory: apps/mgmt-ui/web
      - name: Guard against skipped tests
        run: |
          if rg -n "(it|describe)\\.skip\(" apps/mgmt-ui/web/src --glob "*.test.tsx" -S; then \
            echo "Found skipped tests" >&2; exit 1; \
          else \
            echo "No skipped tests"; \
          fi
      - name: Build
        run: just build
      - name: Commit message guard
        run: |
          MSG=$(git log -1 --pretty=%s)
          echo "Last commit: $MSG"
          if ! echo "$MSG" | grep -Eq '^(feat|fix|chore|docs|test|refactor|perf|ci)(\([\w\-]+\))?: .+'; then
            echo "Commit message does not follow conventional format" >&2
          exit 1
          fi

  web-tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps
        run: pnpm install --frozen-lockfile=false
        working-directory: apps/mgmt-ui/web
      - name: Run vitest (jsdom)
        run: pnpm vitest run --environment jsdom
        working-directory: apps/mgmt-ui/web
