name: Release Windows UI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install frontend deps
        shell: pwsh
        run: |
          if (Test-Path 'apps/mgmt-ui/web/package.json') { pnpm -C apps/mgmt-ui/web i } elseif (Test-Path 'apps/mgmt-ui/package.json') { pnpm -C apps/mgmt-ui i }

      - name: Ensure tauri CLI dev-dep
        run: pnpm -C apps/mgmt-ui add -D @tauri-apps/cli

      - name: Build Tauri UI
        run: pnpm -C apps/mgmt-ui tauri build

      - name: Build CLI (optional)
        run: cargo build -p cli --release

      - name: Gather artifacts
        id: gather
        shell: pwsh
        run: |
          $ver = (Get-Content Cargo.toml | Select-String -Pattern 'version\s*=\s*"([^"]+)' -AllMatches | Select-Object -First 1).Matches.Groups[1].Value
          echo "version=$ver" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          New-Item -ItemType Directory -Force -Path dist\v$ver\windows-x64\mgmt-ui | Out-Null
          if (Test-Path apps\mgmt-ui\src-tauri\target\release\bundle) { Copy-Item -Recurse -Force apps\mgmt-ui\src-tauri\target\release\bundle\* dist\v$ver\windows-x64\mgmt-ui }
          if (Test-Path target\release\cli.exe) { Copy-Item -Force target\release\cli.exe dist\v$ver\windows-x64\ }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chip-tycoon-windows-x64-v${{ steps.gather.outputs.version }}
          path: dist/v${{ steps.gather.outputs.version }}/windows-x64/**

